app-id: org.jcryptool.www.application
runtime: org.freedesktop.Platform
runtime-version: '21.08'
sdk: org.freedesktop.Sdk
sdk-extensions:
  - org.freedesktop.Sdk.Extension.openjdk11
command: JCrypTool
finish-args:
  - --share=network
  - --socket=x11
  - --share=ipc
  - --device=dri
  - --socket=pulseaudio
  - --filesystem=xdg-download
  - --allow=devel
  - --socket=session-bus
  - --socket=wayland
  - --env=PATH=/app/bin:/app/jre/bin:/usr/bin
  - --env=JAVA_HOME=/app/jre
  - --env=GDK_BACKEND=x11
modules:
  - name: jcryptool
    buildsystem: simple
    build-options:
      env:
        PATH: /app/bin:/usr/bin:/usr/lib/sdk/openjdk11/bin
    build-commands:
      - mv jcryptool /app/
      - mkdir /app/bin
      - ln -s /app/jcryptool/JCrypTool /app/bin/
      - install -Dm644 -t "${FLATPAK_DEST}/share/applications" "org.jcryptool.www.application.desktop"
    sources:
      - type: archive
        url: https://github.com/jcryptool/core/releases/download/1.0.8/JCrypTool-1.0.8-Linux-64bit.zip
        sha256: e4d105ec896524c919b6c3184e97923576910425658372b8881be50a4c55447c
        strip-components: 0
        archive-type: "tar-gzip"
      - type: file
        url: https://raw.githubusercontent.com/deknos/org.jcryptool.www/main/org.jcryptool.www.application.desktop
        sha256: d3d1a03e62f2bf2c3a8dda72915fdf83b31fd0e8783d3296e086a2f19ccaeea4

